[window]
title = "Alacritty"
dynamic_title = true
decorations = "None"
dimensions = { columns = 135, lines = 35 }
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 0.98
blur = true
resize_increments = true
startup_mode = "Windowed"
class = { general = "Alacritty", instance = "Alacritty" }

# [scrolling]
# history = 10000
# multiplier = 3

[font]
size = 11.6
offset = { x = 0, y =0 }

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[env]
TERM = "alacritty"

[general]
live_config_reload = true
# Install alacritty-theme
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

# [selection]
# save_to_clipboard = true

[terminal]

[terminal.shell]
program = "zellij"

# 禁用所有的alacritty快捷键，防止跟zellij的快捷键冲突
[keyboard]
bindings = []
